void WeaponShop(int NOP,int PlayerNo){//Generates weapon shop where players can select weapons.
    if (NOP==1){n=4;}
    else{
        if(PlayerNo==1){n=5;}
        else {n=6;}
    }
    Count=0;
    ClearScreen();
    //Loading the Weaponshop Background for the Single Player
    WeaponShopBmp.Load("WeaponShopBackground1.xpm"); 
    WeaponShopBmp.SetPosition(Position(0,-1.0));
	WeaponShopBmp.Draw();
    
    
    if(PlayerNo==1)
    {//Loading the Weaponshop background for first player 
    WeaponShopBmp.Load("WeaponShopBackground1.xpm"); 
    WeaponShopBmp.SetPosition(Position(0,-1.0));
	 WeaponShopBmp.Draw();
        
    }
    else {//Loading the Weaponshop background for second player 
    WeaponShopBmp.Load("WeaponShopBackground2.xpm"); 
    WeaponShopBmp.SetPosition(Position(0,-1.0));
	WeaponShopBmp.Draw();
    
    }
    
    //PocketTanks.RenderRectangle(Position(0,Height/10),Position(Width,Height*7/10),Black);
    //These variables declared below store the name of the images and icons and 
    //the loop given below places them in place.
    char IconBmp[20];
    char NameBmp[20];
    
    for(int i=1;i<=8;i++){
    
        sprintf(IconBmp,"WeaponIcon%d.xpm",i);
        sprintf(NameBmp,"WeaponName%d.xpm",i);
    
        WeaponIcon[i].Load(IconBmp); 
        PhotoPosition = Position(Width/16*3,Height/80*(24 + 6*i)) + Position(-0.5*WeaponIcon[i].GetWidth(),-0.5*WeaponIcon[i].GetHeight());
        WeaponIcon[i].SetPosition(PhotoPosition);
        WeaponIcon[i].Draw();

        WeaponName[i].Load(NameBmp); 
        PhotoPosition = Position(Width/16*5,Height/80*(24 + 6*i)) + Position(-0.5*WeaponName[i].GetWidth(),-0.5*WeaponName[i].GetHeight());
        WeaponName[i].SetPosition(PhotoPosition);
        WeaponName[i].Draw();
    
    }

}




void WeaponSelection(){//User can select which weapon to fire.
     //The char array declared here is used to store name of the bitmap and icon.
    char IconBmp[20];
    char NameBmp[20];
    //The loop checks if there has been a mouse click on each of the weapon and then erases 
    //ones one which mouse click has been recieved and then pastes the image on the right hand side
    //i.e. on the selected side.
    for(int i=1;i<=8;i++){
    
        sprintf(IconBmp,"WeaponIcon%d.xpm",i);
        sprintf(NameBmp,"WeaponName%d.xpm",i);

        if( ((WeaponIcon[i].IsInside(MouseClick)&&Weapon1Chance[i-1]==0&&n==5)||(WeaponName[i].IsInside(MouseClick)&&Weapon1Chance[i-1]==0&&n==5))||
            ((WeaponIcon[i].IsInside(MouseClick)&&Weapon2Chance[i-1]==0&&n==6)||(WeaponName[i].IsInside(MouseClick)&&Weapon2Chance[i-1]==0&&n==6))|| 
            ((WeaponIcon[i].IsInside(MouseClick)&&Weapon1Chance[i-1]==0&&n==4)||(WeaponName[i].IsInside(MouseClick)&&Weapon1Chance[i-1]==0&&n==4))    )

    //The arrays WeaponChance stores how many turns each weapon has played,
    //Each element is initialised with zero and once a weapon is used the correspoding element becomes 1 
    //and the weapon can't be used again.
    //The variable Count keeps track of how many weapons have been selected.
    //The position of the selected weapons is also based on the value of Count.
         {
            WeaponIcon[i].Erase();
            WeaponName[i].Erase();
            
            PhotoPosition = Position(Width/16*3,Height/80*(24 + 6*i)) + Position(-0.5*WeaponIcon[i].GetWidth(),-0.5*WeaponIcon[i].GetHeight());
            PocketTanks.RenderRectangle(PhotoPosition,Position(Width/16*5+0.5*WeaponName[i].GetWidth()+0.1,(Height/80*(24 + 6*i))+0.5*WeaponName[i].GetHeight()+0.1),Black);

			WeaponIcon[i].Load(IconBmp); 
            PhotoPosition = Position(Width*10/16,Height/80*(30 + 6*Count)) + Position(-0.5*WeaponIcon[i].GetWidth(),-0.5*WeaponIcon[i].GetHeight());
            WeaponIcon[i].SetPosition(PhotoPosition);
            WeaponIcon[i].Draw();            
          
            WeaponName[i].Load(NameBmp); 
            PhotoPosition = Position(Width*11/16,Height/80*(30 + 6*Count)) + Position(-0.5*WeaponIcon[i].GetWidth(),-0.5*WeaponIcon[i].GetHeight());
            WeaponName[i].SetPosition(PhotoPosition);
            WeaponName[i].Draw();        	
                    
            if(n==6){Player2Weapons[Count]=i;Weapon2Chance[i-1]++;}
            else {Player1Weapons[Count]=i;Weapon1Chance[i-1]++;}
            Count++;
            
        }
    }
	    
    if(Count==5){
		if(n==4){CpuWeaponSelection();}
        if(n==4||n==6){GamePlayScreen();}
        else {WeaponShop(2,2);}
	}
}

void CpuWeaponSelection(){//This function randomly selects weapons for CPU.
                          //This happens in Single Player mode where the player plays against CPU
	int i,j;	
	srand((unsigned int) time(0));
	for(i=0;i<5;i++){
		//CPU selects a weapon randomly according to the given code.
		//The random selection would be on the basis of a random number generated by the rand()
		//function. The selected weapon will be stored in CpuWeapons[] array.
		CpuWeapons[i]=rand()%8+1;
		for(j=0;j<i;j++){
			while(CpuWeapons[i]==CpuWeapons[j]){CpuWeapons[i]=rand()%8+1;}
		}
	}
	for(i=0;i<5;i++){cout<<CpuWeapons[i]<<endl;}
}
